on:
    workflow_run:
      workflows: [❓ Checkup]
      types:
        - completed
name: 🚀 Deployement
jobs:
    web-deploy: 
        name: 🎉 Déployement Site
        runs-on: ubuntu-latest
        steps:
        - name: 🚚 Copy du code
          uses: actions/checkout@v4
        - name: 📂 Syncronisation fichiers
          uses: SamKirkland/FTP-Deploy-Action@v4.3.5
          with:
            server: ${{ secrets.ftp_server }}
            username: ${{ secrets.ftp_user }}
            password: ${{ secrets.ftp_password }}
            port: 21
            exclude: |
              **/.git*/**
              **/node_modules/**
              **/build/
              .README.MD
              .gitignore
              .htaccess